-- Marks a corpus row that exists only because its artifacts were restored from
-- the vector store, not because the source document was ever captured here.
--
-- The vector payload carries everything an artifact row needs, but nothing
-- about the document it came from: no `raw_text`, no `origin`, no
-- `content_hash`. `artifacts.corpus_id` is NOT NULL and references this table,
-- so an artifact cannot be restored without a parent to point at, and inventing
-- one silently would leave an operator reading a source page that claims to
-- show a captured document while showing reconstructed fragments.
--
-- So the stub is inserted and then labelled. NULL — every ordinary corpus — is
-- "captured here"; a timestamp is "this row is a placeholder, its `raw_text` is
-- the restored artifacts joined together, and re-segmenting it would not
-- reproduce the base". The UI reads exactly this to say so.
ALTER TABLE corpora ADD COLUMN restored_at INTEGER;
